id: PD0D6CD6A
initial_creation_type: input
source_metadata:
  title: Drakkar Lobzang Palden
  language: bo
  description: 'Texts by and about Drakkar Lobzang Palden Tendzin Nyendrak (blo bzang
    dpal ldan bstan ''dzin snyan grags, 1866–1929):'
  volume:
    ebe453dd16af4782ba1bfd46a4603778:
      title: Brief Biography of Drakkar Lobzang Palden
      parent: Biography
created_at: '2022-02-28T23:03:24.784427'
last_modified_at: '2022-02-28T23:03:24.784430'
